### ISSUE TITLE
why

### ISSUE THREAD

**Issue by williamdes** [GetABoard/RewardTest#3]
https://github.com/GetABoard/RewardTest/blob/5f9616dfd3ce9bde23897737f92be8cfd3f40481/package.json#L2

**Comment by dcjr5150** [comment]
@williamdes What is the issue in reference to?

**Comment by williamdes** [comment]
@dcjr5150 you copied my file, why?

**Comment by dcjr5150** [comment]
I can check with my team that worked on it. I’m
Not sure what happened with that. @williamdes


On Dec 4, 2019, at 5:28 PM, William Desportes <notifications@github.com> wrote:

﻿

@dcjr5150<https://github.com/dcjr5150> you copied my file, why?

**Comment by dcjr5150** [comment]
@williamdes I know we copied the file. What I will do is i will have my team remove/modify the file to fit our needs. I didn't realize what they did. Everyone that is working on it is an intern so I will chat with them and let them know it needs to be changed. Sorry for the issue.

**Comment by williamdes** [comment]
@dcjr5150 okay, thank you!
Not so much an issue anymore is it was not intentional

**Comment by dcjr5150** [comment]
@williamdes Everything should be fixed sorry about that happening.

**Comment by williamdes** [comment]
@dcjr5150 Thank you for fixing this, just curious how you did it ?
Can you tell me the story ?

**Comment by dcjr5150** [comment]
We reinitialized the project, We discussed it over and aren't too sure where that package file was grabbed from. @williamdes
